### ISSUE TITLE
Add a name length check when using the filename to name an assignment.

### ISSUE THREAD

**Issue by GPugnet** [JimGBritt/AzureBlueprint#1]
**Context :**
When an assignment has no name, the script use the filename to generate the assignment name.
Then the name is used to generate the assignment ID.

**Issue :** 
If the name exceeds a maximum length of 48, the API returns a _(400) Bad Request_.
The script does not provide details about the issue.

**Suggested fix :** 
Add a control and raise an error when using a filename longer than 48 characters.
Display more details about the API errors. In this case, the API returns an explicit error message we could display : 
```
"error": {
        "code": "InvalidResourceName",
        "message": "The resource name 'policyAssignmentAF_ResourcesGroup_AuditMandatoryTags' exceeds the maximum length of 48."
    }
```

**Comment by JimGBritt** [comment]
Great feedback.  Let me investigate what the best options are here.

**Comment by JimGBritt** [comment]
@GPugnet  - I have validated with the Blueprint team that this specific limit is not an ARM limit but a limit imposed by the Blueprint feature. I'm working on adding some additional validation to ensure that if we hit this limit during import / export that we throw an error and terminate.  Thanks for raising this up.  Will be integrating a fix shortly and publish.

**Comment by JimGBritt** [comment]
@GPugnet could you please review the latest merged version to see if it supports the requirement?  I have also added the ability to run the script on PS CORE with a moduleMode parameter so that you can leverage the Az versus AzureRM Module set.

**Comment by JimGBritt** [comment]
Validated character limit being honored and error thrown on failure.  Closing this issue.
