### ISSUE TITLE
Have a Blueprint Mode Management Group or Subscription

### ISSUE THREAD

**Issue by mrptsai** [JimGBritt/AzureBlueprint#5]
**Context:**

- The Blueprint has been created at a subscription level, not Management Group/Subscription level.
- The Blueprint cannot be exported using Manage-AzureRMBlueprint

I had created Blueprints at the Subscription level only. Could not export using the current version of Manage-AzureRMBlueprint

I modified your script with the following:
**1. New Parameter**
```PowerShell
# Blueprint Mode (Subscription or ManagementGroup)
[Parameter(ParameterSetName='Export')]
[ValidateSet("ManagementGroup","Subscription")]
[string]$BlueprintMode='ManagementGroup',`
```
**2. Listing Management Groups**
```PowerShell
if(!($ManagementGroupID) **-and $BlueprintMode -eq "ManagementGroup")
{
    if($ModuleMode -eq "AzureRM"){[array]$MgtGroupArray = Add-IndexNumberToArray (Get-AzureRmManagementGroup)}
    if($ModuleMode -eq "Az"){[array]$MgtGroupArray = Add-IndexNumberToArray (Get-AzManagementGroup)}
    if(!$MgtGroupArray)
....
```

**3. Get All Blueprints**
```PowerShell
# Get all Blueprints
if ($BlueprintMode -eq "Subscription")
{
    $BlueprintsURI = "https://management.azure.com/subscriptions/$($SubscriptionID)/providers/Microsoft.Blueprint/blueprints?api-version=$($APIVersion)"
} else {
    $BlueprintsURI = "https://management.azure.com/providers/Microsoft.Management/managementGroups/$($ManagementGroupID)/providers/Microsoft.Blueprint/blueprints?api-version=$($APIVersion)"
}
```

**4. No Blueprints found**
```PowerShell
if ($BlueprintMode -eq "Subscription")
{
    write-host "No Blueprints found in $SubscriptionID"
} else
{
    write-host "No Blueprints found in $ManagementGroupID"
}
```

**5. Select a Blueprint**
```PowerShell
if ($BlueprintMode -eq "Subscription")
{
    $BPsArray | Select-Object "#", @{Label = "Blueprint Name";Expression={$_.name}}, @{Label = "Subscription"; Expression = {$($BPsArray.ID).split("/")[2]}}, @{Label = "Blueprint Description";Expression={$_.properties.description}} | ft
} else 
{
    $BPsArray | Select-Object "#", @{Label = "Blueprint Name";Expression={$_.name}}, @{Label = "ManagementGroup"; Expression = {$($BPsArray.ID).split("/")[4]}}, @{Label = "Blueprint Description";Expression={$_.properties.description}} | ft
}
```

**6. Blueprint and Artifacts URI**
```PowerShell
if ($BlueprintMode -eq "Subscription")
{
    $BluePrintURI = "https://management.azure.com/subscriptions/$($SubscriptionID)/providers/Microsoft.Blueprint/blueprints/$($BluePrintName)?api-version=$($APIVersion)"
    $ArtifactsURI = "https://management.azure.com/subscriptions/$($SubscriptionID)/providers/Microsoft.Blueprint/blueprints/$($BluePrintName)/artifacts?api-version=$($APIVersion)"
} else
{
    $BluePrintURI = "https://management.azure.com/providers/Microsoft.Management/managementGroups/$($ManagementGroupID)/providers/Microsoft.Blueprint/blueprints/$($BluePrintName)?api-version=$($APIVersion)"
    $ArtifactsURI = "https://management.azure.com/providers/Microsoft.Management/managementGroups/$($ManagementGroupID)/providers/Microsoft.Blueprint/blueprints/$($BluePrintName)/artifacts?api-version=$($APIVersion)"
}
````

Thanks!

**Comment by JimGBritt** [comment]
Thanks for this sample code.  There are a few other things to do here as you need to ensure that if we are renaming a blueprint that we update that both on export / import.  I'm going through right now and incorporating yours as well as my additional code and will publish a 2.3 here and on PS Gallery.  Thanks for the community support on this @mrptsai - hoping to have this incorporated by end of today or early tomorrow.

**Comment by mrptsai** [comment]
Thanks Jim. 
Thank you for such great script!  
Check out https://dev.azure.com/mrptsai/blueprints.
Kind regards, 
Paul Towler. 
    	
    	

    	Kind regards,
Paul Towler
    
  




On Thu, May 23, 2019 at 8:19 AM +1000, "Jim Britt [MSFT]" <notifications@github.com> wrote:












Thanks for this sample code.  There are a few other things to do here as you need to ensure that if we are renaming a blueprint that we update that both on export / import.  I'm going through right now and incorporating yours as well as my additional code and will publish a 2.3 here and on PS Gallery.  Thanks for the community support on this @mrptsai - hoping to have this incorporated by end of today or early tomorrow.

**Comment by JimGBritt** [comment]
Great project you shared.  I also shared this over to Alex and Satya to make sure they were aware. Thanks for supporting the community!  Closing this as I just updated the script to support the need.  GitHub has it now and PS Gallery will get a push shortly.

**Comment by ajf214** [comment]
Hey Paul,

Hope it's okay that I am reaching out here on the thread. I am no github pro, so not sure if there is a way to message you more directly.

Would love to get a bit more of an understanding of what this project is all about. If you are interested in discussing, please reach out to me at alfran@microsoft.com

Thanks!
Alex
